---
services:
  ## Webserver / Reverse-proxy
  # * responsible for TLS termination with let's encrypt or with custom certificates
  # * the volume :/data/ is for acme and :/data/certs/ for custom certificates
  # * read more details at ...
  caddy:
    image: ${IMAGE_CADDY:-lucaslorentz/caddy-docker-proxy:2.8.10-alpine}
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=frontend-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/caddy:/data"
    networks:
      - frontend-net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:2019/metrics || exit 1"]
      start_period: 20s
      interval: 20s
      timeout: 5s
      retries: 3

networks:
  frontend-net:
    name: frontend-net
