name: release-on-vbranch

on:
  push:
    branches:
      - "release-v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get branch name
        id: branch_name
        run: echo "branch_name=$(basename ${GITHUB_REF})" >> $GITHUB_OUTPUT

      - name: Compress release folder
        run: tar -czvf seatable-compose.tar.gz -C release/ .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ startsWith(steps.branch_name.outputs.branch_name, 'release-') && steps.branch_name.outputs.branch_name.substring(8) }}
          files: |
            seatable-compose.tar.gz
