
name: release-on-vbranch

on:
  push:
    branches:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        tag_name: tag_name
        with:
          files: |
           ./release/.*
           ./release/*
