name: release-on-vbranch

on:
  push:
    branches:
      - "release-v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Compress release folder
        run: tar -czvf seatable-compose.tar.gz -C release/ .

      - name: Get tag name
        id: tag_name
        run: echo "tag_name=$(basename ${GITHUB_REF} | sed 's/release-//')" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_name.outputs.tag_name }}
          files: |
            seatable-compose.tar.gz
